#ifndef ROSDYN_UTILITIES__CHAIN_STATUS__H
#define ROSDYN_UTILITIES__CHAIN_STATUS__H

#include <rosdyn_utilities/chain_state_n.h>

namespace rosdyn
{

/**
 * Define the ChainState with a variable number of axis.
 */
using ChainState = ChainStateN<-1>;
typedef ChainState::Ptr  ChainStatePtr;
typedef ChainState::ConstPtr  ChainStateConstPtr;


/**
 * Define the ChainState# iwth a pre-defined number of axes
 */ 

#define DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(nAx)\
using ChainState ## nAx = ChainStateN<nAx>;\
typedef std::shared_ptr<ChainStateN<nAx>      > ChainState ## nAx ## Ptr;\
typedef std::shared_ptr<ChainStateN<nAx> const> ChainState ## nAx ## ConstPtr;\

DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(1)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(2)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(3)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(4)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(5)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(6)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(7)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(8)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(9)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(10)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(11)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(12)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(13)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(15)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(16)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(17)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(18)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(19)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(20)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(21)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(22)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(23)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(24)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(25)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(26)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(27)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(28)
DEFINE_CHAINSTATE_PTR_STATIC_DIMENSION(29)

}



#endif  // rosdyn__CNR_HANDLES_UTILS_H



