# Travis CI instructions

sudo: required
dist: trusty
language: cpp

notifications:
  email:
    on_failure: always
    recipients:
      - iras@itia.cnr.it
env:
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPO=ros
    - ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="melodic" ROS_REPO=ros

script:
  - .industrial_ci/travis.sh 

