# Travis CI instructions

sudo: required
dist: trusty
language: cpp

notifications:
  email:
    on_failure: always
    recipients:
      - ros@pilz.de
env:
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPO=ros
    - ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="melodic" ROS_REPO=ros
install:
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  - catkin_init_workspace
  # Create the devel/setup.bash (run catkin_make with an empty workspace) and
  # source it to set the path variables.
  - cd ~/catkin_ws
  - catkin_make
  - source devel/setup.bash
  # Add the package under integration to the workspace using a symlink.
  - cd ~/catkin_ws/src
  - ln -s $CI_SOURCE_PATH .
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
  
before_script:
  - cd ~/catkin_ws/src
  - wstool init
  - if [[ -f $ROSINSTALL_FILE ]] ; then wstool merge $ROSINSTALL_FILE ; fi
  - wstool up

script:
  - cd ~/catkin_ws/src/industrial_ci
  - .industrial_ci/travis.sh 

