# Travis CI instructions

sudo: required
dist: trusty
language: generic

notifications:
  email:
    on_failure: always
    recipients:
      - ros@pilz.de
env:
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPO=ros
    - ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="melodic" ROS_REPO=ros
install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh

